### ISSUE TITLE
Charge card error on iOS

### ISSUE THREAD

**Issue by folaoluwafemi** [DEVSOG12/flutter_paystack_payment#9]
```
[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: PlatformException(FWFEvaluateJavaScriptError, Failed evaluating JavaScript., Instance of 'NSError', null)
#0      WKWebViewHostApiImpl.evaluateJavaScriptForInstances (package:webview_flutter_wkwebview/src/web_kit/web_kit_api_impls.dart:1010:7)
<asynchronous suspension>
#1      WebKitWebViewPlatformController.runJavascriptReturningResult (package:webview_flutter_wkwebview/src/web_kit_webview_widget.dart:365:28)
<asynchronous suspension>
[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: PlatformException(FWFEvaluateJavaScriptError, Failed evaluating JavaScript., Instance of 'NSError', null)
#0      WKWebViewHostApiImpl.evaluateJavaScriptForInstances (package:webview_flutter_wkwebview/src/web_kit/web_kit_api_impls.dart:1010:7)
<asynchronous suspension>
#1      WebKitWebViewPlatformController.runJavascriptReturningResult (package:webview_flutter_wkwebview/src/web_kit_webview_widget.dart:365:28)
<asynchronous suspension>
[VERBOSE-2:profiler_metrics_ios.mm(203)] Error retrieving thread information: (os/kern) invalid argument
```

I got this error when charging card directly using a test card on iphone 13 pro max simulator, but I still recieved a credit notification from my paystack account 

please any help will be greatly appreciated.

**Comment by DEVSOG12** [comment]
@folaoluwafemi Thank you. 

Please can you put out steps to reproduce the error you encountered?

**Comment by DEVSOG12** [comment]
@folaoluwafemi I have fixed the issue. I will be pushing a new release soon.

**Comment by folaoluwafemi** [comment]
ohh...alright thanks @DEVSOG12

**Comment by DEVSOG12** [comment]
@folaoluwafemi I have now released a new version to fix this issue. [v0.1.2+5](https://pub.dev/packages/flutter_paystack_payment/versions/0.1.2+5).

Thank you!
